import type { Product } from "./types.ts";

// Datos de DEMOSTRACIÓN. Imitan cómo se ven los listados de cada tipo de fuente
// (tiendas de marca, marketplaces, tiendas locales) pero NO son listados reales:
// precios, títulos y vendedores de marketplace son inventados. Las URLs apuntan a
// la portada de cada sitio o a example.com para tiendas ficticias.

const EXTRACTOR = { engine: "claude-opus-5", version: "extract-v0.3" };

export const PRODUCTS: Product[] = [
  {
    id: "casa-misti-royal-beige",
    title: "Chompa Royal Alpaca 18 micras — cuello redondo, color hueso natural",
    source: { site: "Casa Misti (Arequipa)", url: "https://example.com/casa-misti", method: "scrape", retrievedAt: "2026-09-24T08:10:00Z" },
    seller: { name: "Casa Misti Alpaca", city: "Arequipa" },
    productType: "chompa",
    fiber: {
      alpacaPct: 100,
      composition: [{ material: "Royal alpaca", pct: 100 }],
      quality: "ultrafina",
      micron: 18,
      breed: "huacaya",
    },
    color: { name: "Hueso / beige natural", family: "beige", hex: "#DCCBAE", natural: true },
    origin: { region: "puno", detail: "Fibra de Puno, hilado y confección en Arequipa" },
    construction: "tejido_a_maquina",
    weightGrams: 290,
    sizes: ["S", "M", "L"],
    price: { amount: 1190, currency: "PEN", amountPen: 1190 },
    availability: { status: "pocas_unidades", checkedAt: "2026-09-24T08:10:00Z" },
    images: [],
    rawDescription:
      "ROYAL ALPACA 100% - 18 micras. Color natural sin teñir (hueso). Fibra seleccionada de alpacas Huacaya de Puno, hilada y tejida en nuestro taller de Arequipa. Peso aprox. 290 g.",
    evidence: {
      quality: { provenance: "declarado", confidence: 0.9, quote: "ROYAL ALPACA 100% - 18 micras" },
      micron: { provenance: "declarado", confidence: 0.95, quote: "18 micras" },
      breed: { provenance: "declarado", confidence: 0.9, quote: "alpacas Huacaya" },
      natural: { provenance: "declarado", confidence: 0.95, quote: "Color natural sin teñir" },
      origin: { provenance: "declarado", confidence: 0.85, quote: "Fibra seleccionada ... de Puno" },
      alpacaPct: { provenance: "declarado", confidence: 0.95, quote: "100%" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.92, warnings: [] },
  },
  {
    id: "etsy-handknit-beige",
    title: "Hand knit baby alpaca sweater — natural beige, undyed",
    source: { site: "Etsy", url: "https://www.etsy.com/", method: "api", retrievedAt: "2026-09-23T21:40:00Z" },
    seller: { name: "AndeanThreadsStudio", city: "Puno" },
    productType: "chompa",
    fiber: {
      alpacaPct: 100,
      composition: [{ material: "Baby alpaca", pct: 100 }],
      quality: "baby",
      micron: null,
      breed: "huacaya",
    },
    color: { name: "Natural beige", family: "beige", hex: "#D6C3A1", natural: true },
    origin: { region: "puno", detail: "Cooperativa en Puno (declarado por el vendedor)" },
    construction: "tejido_a_mano",
    weightGrams: 480,
    sizes: ["M", "L"],
    price: { amount: 185, currency: "USD", amountPen: 692 },
    availability: { status: "en_stock", checkedAt: "2026-09-23T21:40:00Z" },
    images: [],
    rawDescription:
      "Cozy hand knit sweater made with 100% baby alpaca yarn from a women's cooperative near Lake Titicaca, Puno. Natural undyed beige. Chunky cable knit, very soft!!",
    evidence: {
      quality: { provenance: "declarado", confidence: 0.8, quote: "100% baby alpaca yarn" },
      micron: { provenance: "desconocido", confidence: 0 },
      breed: { provenance: "inferido", confidence: 0.55, quote: "baby alpaca yarn (Huacaya es ~90% de la población)" },
      natural: { provenance: "declarado", confidence: 0.9, quote: "Natural undyed beige" },
      origin: { provenance: "declarado", confidence: 0.75, quote: "near Lake Titicaca, Puno" },
      alpacaPct: { provenance: "declarado", confidence: 0.9, quote: "100% baby alpaca" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.78, warnings: ["Micronaje no declarado", "Raza inferida, no declarada"] },
  },
  {
    id: "sol-alpaca-cuello-alto",
    title: "Chompa cuello alto Baby Alpaca — Oatmeal",
    source: { site: "Sol Alpaca", url: "https://www.solalpaca.com/", method: "scrape", retrievedAt: "2026-09-24T06:00:00Z" },
    seller: { name: "Sol Alpaca" },
    productType: "chompa",
    fiber: {
      alpacaPct: 100,
      composition: [{ material: "Baby alpaca", pct: 100 }],
      quality: "baby",
      micron: null,
      breed: null,
    },
    color: { name: "Oatmeal", family: "beige", hex: "#CDBB9C", natural: true },
    origin: { region: null },
    construction: "tejido_a_maquina",
    weightGrams: 350,
    sizes: ["XS", "S", "M", "L", "XL"],
    price: { amount: 689, currency: "PEN", amountPen: 689 },
    availability: { status: "en_stock", checkedAt: "2026-09-24T06:00:00Z" },
    images: [],
    rawDescription:
      "Chompa de cuello alto tejida en 100% Baby Alpaca en tono natural oatmeal. Hecho en Perú. Lavar a mano en agua fría.",
    evidence: {
      quality: { provenance: "declarado", confidence: 0.85, quote: "100% Baby Alpaca" },
      micron: { provenance: "desconocido", confidence: 0 },
      breed: { provenance: "desconocido", confidence: 0 },
      natural: { provenance: "declarado", confidence: 0.7, quote: "tono natural oatmeal" },
      origin: { provenance: "desconocido", confidence: 0, quote: "Hecho en Perú" },
      alpacaPct: { provenance: "declarado", confidence: 0.95, quote: "100% Baby Alpaca" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.74, warnings: ["Región no declarada (solo 'Hecho en Perú')"] },
  },
  {
    id: "ml-chompa-mujer-beige",
    title: "Chompa Mujer Baby Alpaca Beige Talla M Nueva Temporada",
    source: { site: "Mercado Libre Perú", url: "https://www.mercadolibre.com.pe/", method: "api", retrievedAt: "2026-09-24T09:30:00Z" },
    seller: { name: "ModaAndinaStore", city: "Lima" },
    productType: "chompa",
    fiber: {
      alpacaPct: null,
      composition: [],
      quality: "baby",
      micron: null,
      breed: null,
    },
    color: { name: "Beige", family: "beige", hex: "#D2BE9E", natural: null },
    origin: { region: null },
    construction: null,
    weightGrams: null,
    sizes: ["M"],
    price: { amount: 329, currency: "PEN", amountPen: 329 },
    availability: { status: "en_stock", checkedAt: "2026-09-24T09:30:00Z" },
    images: [],
    rawDescription:
      "Chompa baby alpaca beige muy suave, ideal para el frío. Talla M. Envíos a todo el Perú. Pregunte antes de ofertar.",
    evidence: {
      quality: { provenance: "declarado", confidence: 0.5, quote: "chompa baby alpaca" },
      micron: { provenance: "desconocido", confidence: 0 },
      breed: { provenance: "desconocido", confidence: 0 },
      natural: { provenance: "desconocido", confidence: 0 },
      origin: { provenance: "desconocido", confidence: 0 },
      alpacaPct: { provenance: "desconocido", confidence: 0 },
    },
    extraction: {
      ...EXTRACTOR,
      confidence: 0.45,
      warnings: ["Composición no declarada: 'baby alpaca' puede ser mezcla", "Sin origen ni micronaje"],
    },
  },
  {
    id: "kuna-cardigan-super-baby",
    title: "Cárdigan Super Baby Alpaca — Gris perla",
    source: { site: "Kuna", url: "https://www.kuna.com.pe/", method: "scrape", retrievedAt: "2026-09-24T05:15:00Z" },
    seller: { name: "Kuna" },
    productType: "cardigan",
    fiber: {
      alpacaPct: 100,
      composition: [{ material: "Super baby alpaca", pct: 100 }],
      quality: "super_baby",
      micron: 19.5,
      breed: "huacaya",
    },
    color: { name: "Gris perla", family: "gris", hex: "#B7B2AA", natural: false },
    origin: { region: "arequipa", detail: "Confeccionado en Arequipa" },
    construction: "tejido_a_maquina",
    weightGrams: 320,
    sizes: ["S", "M", "L"],
    price: { amount: 899, currency: "PEN", amountPen: 899 },
    availability: { status: "en_stock", checkedAt: "2026-09-24T05:15:00Z" },
    images: [],
    rawDescription:
      "Cárdigan de líneas limpias en Super Baby Alpaca (19.5 µ). Teñido en tono gris perla. Diseñado y confeccionado en Arequipa, Perú.",
    evidence: {
      quality: { provenance: "declarado", confidence: 0.9, quote: "Super Baby Alpaca" },
      micron: { provenance: "declarado", confidence: 0.9, quote: "19.5 µ" },
      breed: { provenance: "inferido", confidence: 0.6 },
      natural: { provenance: "declarado", confidence: 0.9, quote: "Teñido en tono gris perla" },
      origin: { provenance: "declarado", confidence: 0.7, quote: "confeccionado en Arequipa" },
      alpacaPct: { provenance: "declarado", confidence: 0.85, quote: "Super Baby Alpaca" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.86, warnings: ["Origen = lugar de confección, no de la fibra"] },
  },
  {
    id: "all-alpaca-chal-suri",
    title: "Chal Baby Suri 100% — crema natural, flecos a mano",
    source: { site: "All Alpaca", url: "https://example.com/all-alpaca", method: "scrape", retrievedAt: "2026-09-22T17:00:00Z" },
    seller: { name: "All Alpaca" },
    productType: "chal",
    fiber: {
      alpacaPct: 100,
      composition: [{ material: "Baby suri alpaca", pct: 100 }],
      quality: "baby",
      micron: 21,
      breed: "suri",
    },
    color: { name: "Crema natural", family: "blanco", hex: "#EEE6D6", natural: true },
    origin: { region: "puno" },
    construction: "telar",
    weightGrams: 210,
    sizes: ["190 × 70 cm"],
    price: { amount: 420, currency: "PEN", amountPen: 420 },
    availability: { status: "en_stock", checkedAt: "2026-09-22T17:00:00Z" },
    images: [],
    rawDescription:
      "Chal tejido en telar con 100% Baby Suri (aprox. 21 micras) de Puno. Brillo sedoso característico de la fibra Suri. Color crema natural, sin tintes. 190x70cm.",
    evidence: {
      quality: { provenance: "declarado", confidence: 0.9, quote: "100% Baby Suri" },
      micron: { provenance: "declarado", confidence: 0.8, quote: "aprox. 21 micras" },
      breed: { provenance: "declarado", confidence: 0.95, quote: "Baby Suri" },
      natural: { provenance: "declarado", confidence: 0.95, quote: "sin tintes" },
      origin: { provenance: "declarado", confidence: 0.85, quote: "de Puno" },
      alpacaPct: { provenance: "declarado", confidence: 0.95, quote: "100%" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.9, warnings: [] },
  },
  {
    id: "ml-chompa-hombre-puno",
    title: "Chompa Alpaca Hombre Cuello V Tejido Puno Oferta!!",
    source: { site: "Mercado Libre Perú", url: "https://www.mercadolibre.com.pe/", method: "api", retrievedAt: "2026-09-24T09:30:00Z" },
    seller: { name: "TextilesAltiplano", city: "Juliaca" },
    productType: "chompa",
    fiber: {
      alpacaPct: 70,
      composition: [
        { material: "Alpaca", pct: 70 },
        { material: "Acrílico", pct: 30 },
      ],
      quality: "fleece",
      micron: null,
      breed: null,
    },
    color: { name: "Marrón chocolate", family: "marron", hex: "#5E4030", natural: null },
    origin: { region: "puno", detail: "Juliaca, Puno" },
    construction: "tejido_a_maquina",
    weightGrams: null,
    sizes: ["M", "L", "XL"],
    price: { amount: 159, currency: "PEN", amountPen: 159 },
    availability: { status: "en_stock", checkedAt: "2026-09-24T09:30:00Z" },
    images: [],
    rawDescription:
      "CHOMPA DE ALPACA PARA HOMBRE cuello V, 70% alpaca 30% acrílico, tejido en Puno. Abrigadora. Tallas M L XL. Somos fabricantes en Juliaca!!",
    evidence: {
      quality: { provenance: "inferido", confidence: 0.4, quote: "70% alpaca (sin calidad declarada; precio y mezcla sugieren fleece)" },
      micron: { provenance: "desconocido", confidence: 0 },
      breed: { provenance: "desconocido", confidence: 0 },
      natural: { provenance: "desconocido", confidence: 0 },
      origin: { provenance: "declarado", confidence: 0.8, quote: "tejido en Puno ... Juliaca" },
      alpacaPct: { provenance: "declarado", confidence: 0.95, quote: "70% alpaca 30% acrílico" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.6, warnings: ["Calidad inferida por el agente, no declarada"] },
  },
  {
    id: "awana-poncho-telar",
    title: "Poncho tejido en telar de cintura — tintes naturales",
    source: { site: "Awana Textil (Cusco)", url: "https://example.com/awana-textil", method: "manual", retrievedAt: "2026-09-18T12:00:00Z" },
    seller: { name: "Awana Textil", city: "Cusco" },
    productType: "poncho",
    fiber: {
      alpacaPct: 100,
      composition: [{ material: "Alpaca", pct: 100 }],
      quality: null,
      micron: null,
      breed: "huacaya",
    },
    color: { name: "Grana y índigo (tintes naturales)", family: "multicolor", hex: "#8E3B2E", natural: false },
    origin: { region: "cusco", detail: "Chinchero, Cusco" },
    construction: "telar",
    weightGrams: 900,
    sizes: ["Talla única"],
    price: { amount: 540, currency: "PEN", amountPen: 540 },
    availability: { status: "desconocido", checkedAt: "2026-09-18T12:00:00Z" },
    images: [],
    rawDescription:
      "Poncho tejido en telar de cintura por tejedoras de Chinchero. 100% alpaca Huacaya, teñido con cochinilla (grana) e índigo. Pieza única.",
    evidence: {
      quality: { provenance: "desconocido", confidence: 0 },
      micron: { provenance: "desconocido", confidence: 0 },
      breed: { provenance: "declarado", confidence: 0.9, quote: "alpaca Huacaya" },
      natural: { provenance: "declarado", confidence: 0.95, quote: "teñido con cochinilla (grana) e índigo" },
      origin: { provenance: "declarado", confidence: 0.9, quote: "tejedoras de Chinchero" },
      alpacaPct: { provenance: "declarado", confidence: 0.9, quote: "100% alpaca" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.8, warnings: ["Ficha cargada manualmente (tienda sin web)", "Stock no verificable"] },
  },
  {
    id: "sol-alpaca-chullo",
    title: "Chullo Baby Alpaca — terracota",
    source: { site: "Sol Alpaca", url: "https://www.solalpaca.com/", method: "scrape", retrievedAt: "2026-09-24T06:00:00Z" },
    seller: { name: "Sol Alpaca" },
    productType: "gorro",
    fiber: {
      alpacaPct: 100,
      composition: [{ material: "Baby alpaca", pct: 100 }],
      quality: "baby",
      micron: null,
      breed: null,
    },
    color: { name: "Terracota", family: "rojo", hex: "#A5553C", natural: false },
    origin: { region: null },
    construction: "tejido_a_maquina",
    weightGrams: 80,
    sizes: ["Única"],
    price: { amount: 129, currency: "PEN", amountPen: 129 },
    availability: { status: "agotado", checkedAt: "2026-09-24T06:00:00Z" },
    images: [],
    rawDescription: "Chullo con orejeras en 100% Baby Alpaca, color terracota. Hecho en Perú.",
    evidence: {
      quality: { provenance: "declarado", confidence: 0.85, quote: "100% Baby Alpaca" },
      micron: { provenance: "desconocido", confidence: 0 },
      breed: { provenance: "desconocido", confidence: 0 },
      natural: { provenance: "inferido", confidence: 0.8, quote: "terracota no es un color natural de alpaca" },
      origin: { provenance: "desconocido", confidence: 0 },
      alpacaPct: { provenance: "declarado", confidence: 0.95, quote: "100% Baby Alpaca" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.76, warnings: [] },
  },
  {
    id: "kuna-manta-blend",
    title: "Manta Alpaca Blend — gris jaspeado",
    source: { site: "Kuna", url: "https://www.kuna.com.pe/", method: "scrape", retrievedAt: "2026-09-24T05:15:00Z" },
    seller: { name: "Kuna" },
    productType: "home",
    fiber: {
      alpacaPct: 60,
      composition: [
        { material: "Alpaca", pct: 60 },
        { material: "Lana de oveja", pct: 40 },
      ],
      quality: null,
      micron: null,
      breed: null,
    },
    color: { name: "Gris jaspeado natural", family: "gris", hex: "#8F8A82", natural: true },
    origin: { region: null },
    construction: "telar",
    weightGrams: 1100,
    sizes: ["130 × 180 cm"],
    price: { amount: 780, currency: "PEN", amountPen: 780 },
    availability: { status: "en_stock", checkedAt: "2026-09-24T05:15:00Z" },
    images: [],
    rawDescription: "Manta tejida en telar. 60% alpaca, 40% lana. Colores naturales jaspeados, sin teñir. 130x180 cm.",
    evidence: {
      quality: { provenance: "desconocido", confidence: 0 },
      micron: { provenance: "desconocido", confidence: 0 },
      breed: { provenance: "desconocido", confidence: 0 },
      natural: { provenance: "declarado", confidence: 0.9, quote: "sin teñir" },
      origin: { provenance: "desconocido", confidence: 0 },
      alpacaPct: { provenance: "declarado", confidence: 0.95, quote: "60% alpaca, 40% lana" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.82, warnings: [] },
  },
  {
    id: "ml-ovillo-baby-puno",
    title: "Hilo Baby Alpaca 100% Natural Pack 5 Ovillos 100g Puno",
    source: { site: "Mercado Libre Perú", url: "https://www.mercadolibre.com.pe/", method: "api", retrievedAt: "2026-09-24T09:30:00Z" },
    seller: { name: "HilanderíaLaraqueri", city: "Puno" },
    productType: "fibra",
    fiber: {
      alpacaPct: 100,
      composition: [{ material: "Baby alpaca", pct: 100 }],
      quality: "baby",
      micron: 22.5,
      breed: "huacaya",
    },
    color: { name: "Blanco natural", family: "blanco", hex: "#F1ECE1", natural: true },
    origin: { region: "puno" },
    construction: null,
    weightGrams: 500,
    sizes: ["5 × 100 g"],
    price: { amount: 95, currency: "PEN", amountPen: 95 },
    availability: { status: "en_stock", checkedAt: "2026-09-24T09:30:00Z" },
    images: [],
    rawDescription:
      "Pack x5 ovillos hilo 100% baby alpaca huacaya 22.5 mic, color blanco natural sin teñir. Grosor DK. Hilado en Puno.",
    evidence: {
      quality: { provenance: "declarado", confidence: 0.9, quote: "100% baby alpaca" },
      micron: { provenance: "declarado", confidence: 0.85, quote: "22.5 mic" },
      breed: { provenance: "declarado", confidence: 0.9, quote: "huacaya" },
      natural: { provenance: "declarado", confidence: 0.95, quote: "sin teñir" },
      origin: { provenance: "declarado", confidence: 0.85, quote: "Hilado en Puno" },
      alpacaPct: { provenance: "declarado", confidence: 0.95, quote: "100%" },
    },
    extraction: { ...EXTRACTOR, confidence: 0.9, warnings: [] },
  },
  {
    id: "etsy-suri-roving",
    title: "Suri alpaca roving for spinning, 22 micron — natural fawn, 200g",
    source: { site: "Etsy", url: "https://www.etsy.com/", method: "api", retrievedAt: "2026-09-23T21:40:00Z" },
    seller: { name: "FiberFromTheAndes" },
    productType: "fibra",
    fiber: {
      alpacaPct: 100,
      composition: [{ material: "Suri alpaca", pct: 100 }],
      quality: "baby",
      micron: 22,
      breed: "suri",
    },
    color: { name: "Fawn natural", family: "camel", hex: "#B08A62", natural: true },
    origin: { region: null, detail: "'Sourced from Peru'" },
    construction: null,
    weightGrams: 200,
    sizes: ["200 g"],
    price: { amount: 38, currency: "USD", amountPen: 142 },
    availability: { status: "pocas_unidades", checkedAt: "2026-09-23T21:40:00Z" },
    images: [],
    rawDescription:
      "Lustrous Suri alpaca combed top / roving, avg 22 micron, natural fawn color. Sourced from Peru. Great for spinning and felting.",
    evidence: {
      quality: { provenance: "inferido", confidence: 0.85, quote: "avg 22 micron → Baby (20.1–23)" },
      micron: { provenance: "declarado", confidence: 0.9, quote: "avg 22 micron" },
      breed: { provenance: "declarado", confidence: 0.95, quote: "Suri alpaca" },
      natural: { provenance: "declarado", confidence: 0.9, quote: "natural fawn color" },
      origin: { provenance: "desconocido", confidence: 0, quote: "Sourced from Peru" },
      alpacaPct: { provenance: "inferido", confidence: 0.7 },
    },
    extraction: { ...EXTRACTOR, confidence: 0.83, warnings: ["Región no declarada"] },
  },
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export const SOURCES = [...new Set(PRODUCTS.map((p) => p.source.site))];
